# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    jsonRequestListener:
        class: ApiBundle\EventListener\JsonRequestListener
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
          - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    published_message.listener:
        class: ApiBundle\EventListener\PublishedMessageExceptionListener
        tags:
        - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }


imports:
    - { resource: "@ApiBundle/Resources/config/services.yml"}