index_route:
  path: /
  defaults:
    _controller: ApiBundle:Index:index

fv_route:
  path: /fv/{id}
  defaults:
    _controller: ApiBundle:Invoice:view

fv_duplicate_route:
  path: /fv/{id}/{duplicate}
  defaults:
    _controller: ApiBundle:Invoice:view

login_route:
  path: /user/login
  methods: [POST]
  defaults:
    _controller: ApiBundle:User:login
getUserInfo_route:
    path: /user/getUserInfo
    defaults:
      _controller: ApiBundle:User:getUserInfo
logout_route:
  path: /user/logout
  defaults:
    _controller: ApiBundle:User:logout
register_route:
  path: /user/register
  methods: [POST]
  defaults:
    _controller: ApiBundle:User:register
change-data_route:
  path: /user/changeData
  methods: [POST]
  defaults:
    _controller: ApiBundle:User:changeData
change-pass_route:
  path: /user/changePass
  methods: [POST]
  defaults:
    _controller: ApiBundle:User:changePass

getClientList_route:
  path: /client/getList
  defaults:
    _controller: ApiBundle:Client:getClientList
getClient_route:
  path: /client/get
  defaults:
    _controller: ApiBundle:Client:getClient
updateClient_route:
  path: /client/update
  methods: [POST]
  defaults:
    _controller: ApiBundle:Client:updateClient

getOrderList_route:
  path: /order/getList
  defaults:
    _controller: ApiBundle:Order:getList
getOpenedOrder_route:
  path: /order/getOpened
  defaults:
    _controller: ApiBundle:Order:getOpened
getOrder_route:
  path: /order/get
  methods: [POST]
  defaults:
    _controller: ApiBundle:Order:get
addOrder_route:
  path: /order/add
  methods: [POST]
  defaults:
    _controller: ApiBundle:Order:add
closeOrder_route:
  path: /order/close
  methods: [POST]
  defaults:
    _controller: ApiBundle:Order:close

getSectionList_route:
  path: /section/getList
  methods: [POST]
  defaults:
    _controller: ApiBundle:Section:getList
getSection_route:
  path: /section/get
  methods: [POST]
  defaults:
    _controller: ApiBundle:Section:getSection
updateSection_route:
  path: /section/update
  methods: [POST]
  defaults:
    _controller: ApiBundle:Section:update
deleteSection_route:
  path: /section/delete
  methods: [POST]
  defaults:
    _controller: ApiBundle:Section:delete

getUnitList_route:
  path: /unit/getList
  methods: [POST]
  defaults:
    _controller: ApiBundle:MeasureUnit:getList
getUnit_route:
  path: /unit/get
  methods: [POST]
  defaults:
    _controller: ApiBundle:MeasureUnit:getUnit
updateUnit_route:
  path: /unit/update
  methods: [POST]
  defaults:
    _controller: ApiBundle:MeasureUnit:update
deleteUnit_route:
  path: /unit/delete
  methods: [POST]
  defaults:
    _controller: ApiBundle:MeasureUnit:delete

getPaymentList_route:
  path: /payment/getList
  methods: [POST]
  defaults:
    _controller: ApiBundle:PaymentMethod:getList
getPayment_route:
  path: /payment/get
  methods: [POST]
  defaults:
    _controller: ApiBundle:PaymentMethod:getMethod
updatePayment_route:
  path: /payment/update
  methods: [POST]
  defaults:
    _controller: ApiBundle:PaymentMethod:update
deletePayment_route:
  path: /payment/delete
  methods: [POST]
  defaults:
    _controller: ApiBundle:PaymentMethod:delete

recaptcha_route:
  path: /recaptcha
  methods: [POST]
  defaults:
    _controller: ApiBundle:recaptcha:valid

acceptInvoice_route:
  path: /invoice/accept/{id}
  methods: [GET]
  defaults:
    _controller: ApiBundle:Invoice:accept
removrInvoice_route:
  path: /invoice/remove/{id}
  methods: [GET]
  defaults:
    _controller: ApiBundle:Invoice:remove
getPaymentMethod_route:
  path: /invoice/payment
  methods: [GET]
  defaults:
    _controller: ApiBundle:Invoice:getPaymentMethods
getNonConsideredInvoides_route:
  path: /invoice/get/NonConsidered
  methods: [GET]
  defaults:
    _controller: ApiBundle:Invoice:getNonConsidered
addInvoice_route:
  path: /invoice/add
  methods: [POST]
  defaults:
    _controller: ApiBundle:Invoice:add
editInvoice_route:
  path: /invoice/edit
  methods: [POST]
  defaults:
    _controller: ApiBundle:Invoice:edit
getMinInvoiceDate_route:
  path: /invoice/getMinDate
  methods: [GET]
  defaults:
    _controller: ApiBundle:Invoice:getMinDate
getInvoice_route:
  path: /invoice/get/{id}
  methods: [GET]
  defaults:
    _controller: ApiBundle:Invoice:get
getFirnstInvoiceYear_route:
  path: /invoice/getFirstInvoiceYear
  methods: [GET]
  defaults:
    _controller: ApiBundle:Invoice:getFirstInvoiceYear
getInvoiceList_route:
  path: /invoice/getList
  methods: [GET]
  defaults:
    _controller: ApiBundle:Invoice:getList
getClientsWithInvoices_route:
  path: /invoice/getClientsWithInvoices
  methods: [GET]
  defaults:
    _controller: ApiBundle:Invoice:getClientsWithInvoices

viewinternalRegister:
  path: /register/view/internal
  methods: [GET]
  defaults:
    _controller: ApiBundle:Register:viewInternal
viewRegister:
  path: /register/view/{year}/{month}/{type}
  methods: [GET]
  defaults:
    _controller: ApiBundle:Register:view
viewSummary:
  path: /register/summary/{year}/{month}
  methods: [GET]
  defaults:
    _controller: ApiBundle:Register:summary
getJpk:
  path: /jpk/{year}/{month}/{number}
  methods: [GET]
  defaults:
    _controller: ApiBundle:Register:getJpk

addPurchase:
  path: /purchase/AddPurchase
  methods: [POST]
  defaults:
    _controller: ApiBundle:Purchase:add
listRegister:
  path: /purchase/list
  methods: [GET]
  defaults:
    _controller: ApiBundle:Purchase:list
isRegisteredPurchase:
  path: /purchase/isRegistered
  methods: [GET]
  defaults:
    _controller: ApiBundle:Purchase:isRegistered

getPurchase:
  path: /purchase/get/{id}
  methods: [GET]
  defaults:
    _controller: ApiBundle:Purchase:get
removePurchase:
  path: /purchase/remove/{id}
  methods: [GET]
  defaults:
    _controller: ApiBundle:Purchase:remove
listPurchase:
  path: /purchase/getList
  methods: [GET]
  defaults:
    _controller: ApiBundle:Purchase:getList
getFirstInvoiceYear_purchase_route:
  path: /purchase/getFirstInvoiceYear
  methods: [GET]
  defaults:
    _controller: ApiBundle:Purchase:getFirstInvoiceYear
getClientsWithInvoices_purchase_route:
  path: /purchase/getClientsWithInvoices
  methods: [GET]
  defaults:
    _controller: ApiBundle:Purchase:getClientsWithInvoices

