services:
  phpass_service:
      class: ApiBundle\Service\PHPass
      arguments: [8, false]
  user_service:
    class: ApiBundle\Service\User
    arguments: [ "@doctrine.orm.entity_manager", "@phpass_service" ]
