services:
  PHPass_manager:
      class: ApiBundle\Service\PHPass
      arguments: [8, false]
  user_manager:
    class: ApiBundle\Service\User
    arguments: [ "@doctrine.orm.entity_manager", "@PHPass_manager" ]
